"use server"

import { signIn, signOut } from "../auth";
import { connectToDb } from "../database/db";
import { Blog, User } from "../models/models";
// import { unstable_noStore as noStore } from "next/cache";
import bcrypt from "bcryptjs";


// Blogs Server Actions

export const getBlogs = async () => {
  try {
    connectToDb();
    const blogs = await Blog.find();
    return blogs;
  } catch (err) {
    console.log(err);
    throw new Error("Failed to fetch blogs!");
  }
};

export const getBlog = async (slug) => {
  try {
    connectToDb();
    const blog = await Blog.findOne({ slug });
    return blog;
  } catch (err) {
    console.log(err);
    throw new Error("Failed to fetch blog!");
  }
};

export const addBlog = async (prevState,formData) => {
  // const title = formData.get("title");
  // const desc = formData.get("desc");
  // const slug = formData.get("slug");

  const { title, desc, slug, userId } = Object.fromEntries(formData);

  try {
    connectToDb();
    const newBlog = new Blog({
      title,
      desc,
      slug,
      userId,
    });

    await newBlog.save();
    console.log("saved to db");
    revalidatePath("/blog");
    revalidatePath("/admin");
  } catch (err) {
    console.log(err);
    return { error: "Something went wrong!" };
  }
};

export const deleteBlog = async (formData) => {
  const { id } = Object.fromEntries(formData);

  try {
    connectToDb();

    await Blog.findByIdAndDelete(id);
    console.log("deleted from db");
    revalidatePath("/blog");
    revalidatePath("/admin");
  } catch (err) {
    console.log(err);
    return { error: "Something went wrong!" };
  }
};

// User Server Actions

export const getUser = async (id) => {
  // noStore();
  try {
    connectToDb();
    const user = await User.findById(id);
    return user;
  } catch (err) {
    console.log(err);
    throw new Error("Failed to fetch user!");
  }
};

export const getUsers = async () => {
  try {
    connectToDb();
    const users = await User.find();
    return users;
  } catch (err) {
    console.log(err);
    throw new Error("Failed to fetch users!");
  }
};

export const addUser = async (prevState,formData) => {
  const { username, email, password, img } = Object.fromEntries(formData);

  try {
    connectToDb();
    const newUser = new User({
      username,
      email,
      password,
      img,
    });

    await newUser.save();
    console.log("saved to db");
    revalidatePath("/admin");
  } catch (err) {
    console.log(err);
    return { error: "Something went wrong!" };
  }
};

export const deleteUser = async (formData) => {
  const { id } = Object.fromEntries(formData);

  try {
    connectToDb();

    await Post.deleteMany({ userId: id });
    await User.findByIdAndDelete(id);
    console.log("deleted from db");
    revalidatePath("/admin");
  } catch (err) {
    console.log(err);
    return { error: "Something went wrong!" };
  }
};

//GITHUB LOGIN

export const handleGithubLogin = async () => {
  "use server";
  await signIn("github");
};

//GITHUB LOG OUT

export const handleLogout = async () => {
  "use server";
  await signOut();
};

// NORMAL REGISTER

export const register = async (previousState, formData) => {
  const { username, email, password, img, passwordRepeat } =
    Object.fromEntries(formData);

  if (password !== passwordRepeat) {
    return { error: "Passwords do not match" };
  }

  try {
    connectToDb();

    const user = await User.findOne({ username });

    if (user) {
      return { error: "Username already exists" };
    }

    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    const newUser = new User({
      username,
      email,
      password: hashedPassword,
      img,
    });

    await newUser.save();
    console.log("saved to db");

    return { success: true };
  } catch (err) {
    console.log(err);
    return { error: "Something went wrong!" };
  }
};
// NORMAL LOGIN

export const login = async (prevState, formData) => {
  const { username, password } = Object.fromEntries(formData);

  try {
    await signIn("credentials", { username, password });
  } catch (err) {
    console.log(err);

    if (err.message.includes("CredentialsSignin")) {
      return { error: "Invalid username or password" };
    }
    throw err;
  }
};